### ISSUE TITLE
VM image for virtual box has issues; cortx motr install-build-deps script fails 

### ISSUE THREAD

**Issue by rupasree-roy** [Seagate/cortx#119]
I downloaded the vm image for virtual box mentioned in directory : https://seagatetechnology-my.sharepoint.com/:f:/g/personal/basavaraj_kirunge_seagate_com/EgkMhqmUbIdFs8Tr9N-bHecBtMDwm02QbG0T8vS7TLOdUg?e=aiRHBr. However, while trying to install dependent packages like lustre using 
```
sudo ./scripts/install-build-deps
``` 
it gives the following error 

![image](https://user-images.githubusercontent.com/66809998/89843964-fb574300-db2e-11ea-8580-c316a5d8b222.png)

This directory is part of the 'Local VM setup' https://github.com/Seagate/cortx/blob/master/doc/LocalVMSetup.md#1-download-the-vm

**Comment by Saumya-Sunder** [comment]
Sure @mukul-seagate11 , will do.

**Comment by Saumya-Sunder** [comment]
@gauravchaudhari02 @mukul-seagate11 I still have not got a single component rep to help me document the updated Single VM setup. Kindly provide me some resource who can help me to do the same.

**Comment by mukul-seagate11** [comment]
@madhavemuri, can you look into this & assist Saumya in documenting the same as the issue is related to Lustre

**Comment by madhavemuri** [comment]
I just verified this issue, seems not occurring with latest main branch.

TASK [motr-build : download Lustre src rpm] *****************************************************************************************
ok: [localhost]
stdout:  skipped, since /root/lustre-*.src.rpm exists

TASK [motr-build : install Lustre src rpm] ******************************************************************************************
ok: [localhost]
stdout:  skipped, since /root/rpmbuild/SPECS/lustre.spec exists

TASK [motr-build : install additional Lustre build dependencies] ********************************************************************
ok: [localhost]
results:  patch-2.7.1-12.el7_7.x86_64 providing patch is already installed

TASK [motr-build : apply Lustre spec patch] *****************************************************************************************
ok: [localhost]

TASK [motr-build : disable Lustre rpm strict kernel version check] ******************************************************************
ok: [localhost]

TASK [motr-build : bump local Lustre rpm build number to override stock builds] *****************************************************
ok: [localhost]

TASK [motr-build : install Lustre rpm build dependencies] ***************************************************************************
ok: [localhost]
stdout:  Loaded plugins: fastestmirror, product-id, subscription-manager
Enabling epel-source repository
Loading mirror speeds from cached hostfile
 * epel: dfw.mirror.rackspace.com
 * epel-source: dfw.mirror.rackspace.com
Checking for new repos for mirrors
Getting requirements for /root/rpmbuild/SPECS/lustre.spec
 --> Already installed : libtool-2.4.2-22.el7_3.x86_64
 --> Already installed : libyaml-devel-0.1.4-11.el7_0.x86_64
 --> Already installed : zlib-devel-1.2.7-18.el7.x86_64
 --> Already installed : libselinux-devel-2.5-15.el7.x86_64
 --> Already installed : kernel-devel-3.10.0-1127.el7.x86_64
 --> Already installed : redhat-rpm-config-9.1.0-88.el7.centos.noarch
 --> Already installed : systemd-219-78.el7_9.2.x86_64
 --> Already installed : rsync-3.1.2-10.el7.x86_64
No uninstalled build requires

TASK [motr-build : build Lustre rpms] ***********************************************************************************************
ok: [localhost]
stdout:  skipped, since /root/rpmbuild/RPMS/x86_64/lustre-client-devel-*.rpm exists

TASK [motr-build : read Lustre package version] *************************************************************************************
ok: [localhost]
stdout:  2.12.5-99.el7.x86_64

TASK [motr-build : install local Lustre rpms] ***************************************************************************************
ok: [localhost]
results:
  kmod-lustre-client-2.12.5-99.el7.x86_64 providing /root/rpmbuild/RPMS/x86_64/kmod-lustre-client-2.12.5-99.el7.x86_64.rpm is already installed
  lustre-client-2.12.5-99.el7.x86_64 providing /root/rpmbuild/RPMS/x86_64/lustre-client-2.12.5-99.el7.x86_64.rpm is already installed

TASK [motr-build : clean yum metadata] **********************************************************************************************
ok: [localhost]
stdout:  Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-
              : manager
Cleaning repos: EOS_CentOS-7_CentOS-7-Extras EOS_CentOS-7_CentOS-7-OS
              : EOS_CentOS-7_CentOS-7-Updates EOS_EPEL-7_EPEL-7
              : EOS_Mellanox-EL7_8_mlnx_ofed_4_9-0_1_7_0 EOS_Puppet6_puppet6-el7
              : epel hashicorp lustre-local lustre-whamcloud-2.12.5
              : petersen-stack releases_cortx_s3deps
55 metadata files removed
17 sqlite files removed
0 metadata files removed

TASK [motr-build : create local repo dir] *******************************************************************************************
ok: [localhost]

TASK [motr-build : copy Lustre devel rpm to local repo] *****************************************************************************
ok: [localhost]

**Comment by mukul-seagate11** [comment]
@rupasree-roy, Can you verify If you are still experiencing similar issue? or provide more clarification if issue still exist

**Comment by rupasree-roy** [comment]
@mukul-seagate11 I have created a centos VM from scratch and continuing my work there. Don't think will need a VM image for virtual box at this time. Thank you.
