### ISSUE TITLE
Creating a dummy issue so I can paste some images

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#1324]
![](https://user-images.githubusercontent.com/2047294/141506111-ab0cfbd3-0cf2-41bd-9aa9-052763860c70.png)

![](https://user-images.githubusercontent.com/2047294/141506155-314850b7-2ca3-4b13-a44b-66c22d8c9743.png)

![](https://user-images.githubusercontent.com/2047294/141506212-ba706092-94a6-4aaa-9c2b-8140f8b35425.png)

**Comment by johnbent** [comment]
closing

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26103. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

why is it so hard to close an issue?

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

fixed

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

fixed
