### ISSUE TITLE
Need AWS Cloud Formation template

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#1381]
We now have K8S deployment guide for AWS which works great but has a lot of manual steps. It would be awesome if it was improved with a Cloud Formation template.
https://github.com/Seagate/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md

FYI @gregnsk

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27306. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by trshaffer** [comment]
Currently debugging the guide in seagate/cortx-k8s#103

**Comment by trshaffer** [comment]
PR to provide CloudFormation templates is at Seagate/cortx-k8s#119, will update this repo once that PR lands

**Comment by trshaffer** [comment]
@johnbent the link on the quick start page now points to my new CloudFormation guide, so this issue can be closed

**Comment by johnbent** [comment]
Thanks @trshaffer !
