### ISSUE TITLE
IOR Integration

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#1388]
IOR (and mdtest) is a frequently used performance benchmark. It has an abstract backend interface. It would be great to create a motr backend and it would also be great to test the existing S3 backend against CORTX.
https://github.com/hpc/ior <- main repo
https://github.com/hpc/ior/blob/main/src/aiori.h <- backend interface

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27682. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
