### ISSUE TITLE
Update CORTX on AWS Guide

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx#1402]
CORTX is an open-source object store. It would be great if someone could build CORTX in AWS following this [guide](https://github.com/Seagate/cortx/tree/main/doc/integrations/AWS_EC2) if you could use the latest OVA release and then update this guide to reflect the changes.

As a bonus challenge to make this guide dynamically update to the newest OVA each time a new OVA is released.

You can see the OVA releases [here](https://github.com/Seagate/cortx/releases)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28370. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
