### ISSUE TITLE
Code improvement: replace bubble sort with heap sort

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx#1403]
Currently the file \`motr/io.c\` uses the bubble sort algorithm. As we already know this algorithm has a bad time complexity. One solution to this issue as mentioned in this comment: https://github.com/Seagate/cortx-motr/blob/409f711fcfa22b393e34a14f49eab5fa142131bb/motr/io.c#L136  is to replace bubble sort with heap sort. 

\<br>\<br>

Here is a link to the code in question: [https://github.com/Seagate/cortx-motr/blob/409f711fcfa22b393e34a14f49eab5fa142131bb/motr/io.c#L124](https://github.com/Seagate/cortx-motr/blob/409f711fcfa22b393e34a14f49eab5fa142131bb/motr/io.c#L124)

Here is the link to the issue in the cortx-motr github repo: Seagate/cortx-motr#1424

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28372. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
