### ISSUE TITLE
Code Improvement: Code appears to be redundant

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx#1404]
It would be nice to figure out whether this code is actually redundant or not.

This [comment](https://github.com/Seagate/cortx-motr/blob/409f711fcfa22b393e34a14f49eab5fa142131bb/motr/io.c#L86) suggests that the code may be redundant.

Identify if code is redundant and if not fix comment and mention why it is required.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28373. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
