### ISSUE TITLE
Create installation script for Motr

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx#1406]
The Motr \[Quick Start Guide\](https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst) involves very manual steps of copying and pasting commands to your terminal.

Instead create a script that once you clone the project from GitHub you can just run `./motr_install_script` and Motr will install on your machine.

You can also create this script to install Motr+HARE so once the script is complete you can do read/writes on your system as you will have all the process fids, wtc. required to do reads/writes on Motr.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28375. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by rkothiya** [comment]
We already have such a script in place. You can fire the below command to install motr+hare :
```
cortx-motr/scripts/build-prep-1node.sh -dev
```

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
