### ISSUE TITLE
Network troubleshooting instructions need to be updated

### ISSUE THREAD

**Issue by justinzw** [Seagate/cortx#1440]
These need to be updated as the OVA has changed.

https://github.com/Seagate/cortx/blob/main/doc/troubleshoot_virtual_network.rst

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29015. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
This guide is no longer relevant and so closing issue
