### ISSUE TITLE
Validate CORTX integrations

### ISSUE THREAD

**Issue by justinzw** [Seagate/cortx#1454]
We have a list of CORTX integrations [here](https://github.com/Seagate/cortx/blob/main/doc/integrations/README.rst).

These are community created integrations and many still need validation and testing

You can setup CORTX [here](https://github.com/Seagate/cortx/blob/main/doc/ova/2.0.0/PI-5/CORTX_on_Open_Virtual_Appliance_PI-5.rst).

Choose an integration and then add a "Tested-by" section when you have completed the testing to mark that you have tested.

E.g. https://github.com/Seagate/cortx/tree/main/doc/integrations/AWS_EC2

Or if you have a problem with the integration please raise an issue [here](https://github.com/Seagate/cortx/issues).

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29165. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
