### ISSUE TITLE
Deploy CORTX on a cluster using MINIKUBE

### ISSUE THREAD

**Issue by r-wambui** [Seagate/cortx#1455]
Currently, we can deploy CORTX on Minikube on a [single node](https://github.com/Seagate/cortx-k8s/blob/integration/doc/cortx-minikube-k8s-installation.md)

Deploy CORTX on a cluster(either 2 nodes or 3 nodes). Minikube is quite resource-intensive; to deploy on a cluster will require 2 or 3 virtual machines running concurrently, each with the minimum specification indicated on the single node document.

You can use [this guide](https://github.com/Seagate/cortx-k8s/blob/integration/doc/cortx-aws-k8s-installation.md) which deploys CORTX on a cluster on AWS.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29166. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
