### ISSUE TITLE
Need Issue Templates

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#1477]
The community team needs to create new Issue templates. Here is what it looks like when someone creates a new issue in cortx-k8s:

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/2047294/160910141-88a4fabd-fce4-43cf-b339-efb7a29344d6.png">

We need the same but we also need to add a feature request template.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29856. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by johnbent** [comment]
Done in https://github.com/Seagate/.github/commit/02422bff27b87f3fb54e5d45a5110cc124110b43. Closing.

**Comment by cortx-admin** [comment]
> Rose Wambui commented in Jira Server:

Issue closed in GitHub

**Comment by cortx-admin** [comment]
> Rose Wambui commented in Jira Server:

Closed on Github
