### ISSUE TITLE
exported method Endpoint.Init should have comment or be unexported

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1481]
#### Currently on:
+ **Commit**:  dc4a09c4cc8ff7ce9eff537ce18a389f84579377
+ **File**:    [doc/integrations/drp/DRP-go/drpold/drpclient.go](https://github.com/Seagate/cortx/blob/dc4a09c4cc8ff7ce9eff537ce18a389f84579377/doc/integrations/drp/DRP-go/drpold/drpclient.go)
+ **LineNum**: [26](https://github.com/Seagate/cortx/blob/dc4a09c4cc8ff7ce9eff537ce18a389f84579377/doc/integrations/drp/DRP-go/drpold/drpclient.go#L26)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30722. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.
