### ISSUE TITLE
Possible hardcoded password: 'XXXXXX'

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1492]
#### Currently on:
+ **Commit**:  04557c074918fb7f4bc92b13f79f7862a585f0d0
+ **File**:    [cortx-s3samplecode/python/cortx-s3samplecode-python.py](https://github.com/Seagate/cortx/blob/04557c074918fb7f4bc92b13f79f7862a585f0d0/cortx-s3samplecode/python/cortx-s3samplecode-python.py)
+ **LineNum**: [12](https://github.com/Seagate/cortx/blob/04557c074918fb7f4bc92b13f79f7862a585f0d0/cortx-s3samplecode/python/cortx-s3samplecode-python.py#L12)

**Comment by mukul-seagate11** [comment]
False Positive, hence closing

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31021. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

identified false positive in code

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

issue closed

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.
