### ISSUE TITLE
Unexpected console statement.

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1505]
#### Currently on:
+ **Commit**:  0b9e5e1cd5f42ff590cf7ba6c37d146daea6684b
+ **File**:    [doc/integrations/myDrive/backend/controllers/file.ts](https://github.com/Seagate/cortx/blob/0b9e5e1cd5f42ff590cf7ba6c37d146daea6684b/doc/integrations/myDrive/backend/controllers/file.ts)
+ **LineNum**: [127](https://github.com/Seagate/cortx/blob/0b9e5e1cd5f42ff590cf7ba6c37d146daea6684b/doc/integrations/myDrive/backend/controllers/file.ts#L127)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31250. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

ESLint deprecated as reported, hence ignored

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

ESLint deprecated as reported, hence ignored

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.
