### ISSUE TITLE
[False Positive] Possible hardcoded secret key (secret)

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1511]
#### Currently on:
+ **Commit**:  1a28a619d2bb0ab3a4c889a9b0a9c318a658a76e
+ **File**:    [cortx-s3samplecode/python/cortx-s3samplecode-python.py](https://github.com/Seagate/cortx/blob/1a28a619d2bb0ab3a4c889a9b0a9c318a658a76e/cortx-s3samplecode/python/cortx-s3samplecode-python.py)
+ **LineNum**: [12](https://github.com/Seagate/cortx/blob/1a28a619d2bb0ab3a4c889a9b0a9c318a658a76e/cortx-s3samplecode/python/cortx-s3samplecode-python.py#L12)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31345. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Issue is reported as false positive

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Issue reported as false positive

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.
