### ISSUE TITLE
Expected indentation of 14 spaces (indentation)

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1514]
#### Currently on:
+ **Commit**:  b5604cba1f4d4735fc9c166d7442ce0fb33bffdf
+ **File**:    [doc/integrations/myDrive/src/styles/components/settings.scss](https://github.com/Seagate/cortx/blob/b5604cba1f4d4735fc9c166d7442ce0fb33bffdf/doc/integrations/myDrive/src/styles/components/settings.scss)
+ **LineNum**: [168](https://github.com/Seagate/cortx/blob/b5604cba1f4d4735fc9c166d7442ce0fb33bffdf/doc/integrations/myDrive/src/styles/components/settings.scss#L168)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31452. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

Correct per Stylelint coding standard

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

Correct per Stylelint coding standard

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

Merged and Closed
