### ISSUE TITLE
Expected a conditional expression and instead saw an assignment.

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1520]
#### Currently on:
+ **Commit**:  278bdc471b899bb62c99b57a7f74237328223e0e
+ **File**:    [doc/integrations/myDrive/public/fontawesome/js/fontawesome.min.js](https://github.com/Seagate/cortx/blob/278bdc471b899bb62c99b57a7f74237328223e0e/doc/integrations/myDrive/public/fontawesome/js/fontawesome.min.js)
+ **LineNum**: [5](https://github.com/Seagate/cortx/blob/278bdc471b899bb62c99b57a7f74237328223e0e/doc/integrations/myDrive/public/fontawesome/js/fontawesome.min.js#L5)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31577. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

Inspect by Stylelint no issue and merged to main.

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

Merged to main per PR#1535

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

closed
