### ISSUE TITLE
[no-emphasis-as-heading] Don’t use emphasis to introduce a section, use a heading

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1523]
#### Currently on:
+ **Commit**:  6c26ac60bf5383f80b541e9cb579727b9f9353c6
+ **File**:    [doc/integrations/parlAI/docs/source/tutorial_metrics.md](https://github.com/Seagate/cortx/blob/6c26ac60bf5383f80b541e9cb579727b9f9353c6/doc/integrations/parlAI/docs/source/tutorial_metrics.md)
+ **LineNum**: [208](https://github.com/Seagate/cortx/blob/6c26ac60bf5383f80b541e9cb579727b9f9353c6/doc/integrations/parlAI/docs/source/tutorial_metrics.md#L208)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31650. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
