### ISSUE TITLE
[emphasis-marker] Emphasis should use `_` as a marker

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1525]
#### Currently on:
+ **Commit**:  1d7bacb75c92b1fab51898bc3757f452661dafa2
+ **File**:    [doc/integrations/parlAI/docs/source/tutorial_task.md](https://github.com/Seagate/cortx/blob/1d7bacb75c92b1fab51898bc3757f452661dafa2/doc/integrations/parlAI/docs/source/tutorial_task.md)
+ **LineNum**: [354](https://github.com/Seagate/cortx/blob/1d7bacb75c92b1fab51898bc3757f452661dafa2/doc/integrations/parlAI/docs/source/tutorial_task.md#L354)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31652. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
