### ISSUE TITLE
Codacy Badge is not rendering properly for five docs

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#1528]
### Problem

Codacy Badge sign is not rendering properly in the markdown doc
![image](https://user-images.githubusercontent.com/68423216/171085390-f903880b-6a72-4df1-906d-908d1d41fc52.png)

### Expected behavior

should see the badge clearly as 
![image](https://user-images.githubusercontent.com/68423216/171085368-a3db589e-45f1-4b59-97de-20a873a40aab.png)

### How to reproduce

go to the following doc and will see the rendering problems

https://github.com/Seagate/cortx-experiments/blob/main/README.md

https://github.com/Seagate/cortx-ha/blob/main/README.md

https://github.com/Seagate/cortx-hare/blob/main/README.md

https://github.com/Seagate/cortx-prvsnr/blob/main/README.md

https://github.com/Seagate/cortx-utils/blob/main/README.md

### Deployment information

google chrome web browser

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31845. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
PRs are made to resolve this issue, just waiting for them to be reviewed and merged

**Comment by hessio** [comment]
Will leave open until all 4 PRs are merged cc: @r-wambui

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
