### ISSUE TITLE
'User' was used before it was defined.

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1545]
#### Currently on:
+ **Commit**:  85dc2f16566d014ab74f753678df52edf7cada85
+ **File**:    [doc/integrations/myDrive/backend/models/user.ts](https://github.com/Seagate/cortx/blob/85dc2f16566d014ab74f753678df52edf7cada85/doc/integrations/myDrive/backend/models/user.ts)
+ **LineNum**: [222](https://github.com/Seagate/cortx/blob/85dc2f16566d014ab74f753678df52edf7cada85/doc/integrations/myDrive/backend/models/user.ts#L222)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-32147. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Hi @r-wambui is there any update on this?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
