### ISSUE TITLE
[Codacy Cleanup]: GITHUB ISSUE-Possible SCM diff in code (diff) 2

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1578]
#### Currently on:
+ **Commit**:  a2bee64889e665bb16194c817ebef0a34f0aae02
+ **File**:    [metrics/mk_community_partnership_report.py](https://github.com/Seagate/cortx/blob/a2bee64889e665bb16194c817ebef0a34f0aae02/metrics/mk_community_partnership_report.py)
+ **LineNum**: [51](https://github.com/Seagate/cortx/blob/a2bee64889e665bb16194c817ebef0a34f0aae02/metrics/mk_community_partnership_report.py#L51)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-32544. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Raised PR#1591 to fix the code

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.
