### ISSUE TITLE
[Codacy Cleanup] Using variable 'response' before assignment

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1579]
#### Occurred on:
+ **Commit**:  e0340e54f3be0b1fd9906adb22165188f24f4e2b
+ **File**:    [metrics/scrape_slack.py](https://github.com/Seagate/cortx/blob/e0340e54f3be0b1fd9906adb22165188f24f4e2b/metrics/scrape_slack.py)
+ **LineNum**: [111](https://github.com/Seagate/cortx/blob/e0340e54f3be0b1fd9906adb22165188f24f4e2b/metrics/scrape_slack.py#L111)
+ **Code**:    `cursor = response['response_metadata']['next_cursor']`

    
#### Currently on:
+ **Commit**:  ff80952efb146aa4dbce1b1cc0a2d3cdd635714c
+ **File**:    [metrics/scrape_slack.py](https://github.com/Seagate/cortx/blob/ff80952efb146aa4dbce1b1cc0a2d3cdd635714c/metrics/scrape_slack.py)
+ **LineNum**: [152](https://github.com/Seagate/cortx/blob/ff80952efb146aa4dbce1b1cc0a2d3cdd635714c/metrics/scrape_slack.py#L152)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-32546. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
