### ISSUE TITLE
"vue" is not found.

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1592]
#### Currently on:
+ **Commit**:  f81359d018f9e357a7531949c199114e4ab81e11
+ **File**:    [doc/integrations/edgehealth/edgehealth/src/router/index.js](https://github.com/Seagate/cortx/blob/f81359d018f9e357a7531949c199114e4ab81e11/doc/integrations/edgehealth/edgehealth/src/router/index.js)
+ **LineNum**: [1](https://github.com/Seagate/cortx/blob/f81359d018f9e357a7531949c199114e4ab81e11/doc/integrations/edgehealth/edgehealth/src/router/index.js#L1)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33531. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
