### ISSUE TITLE
Possible hardcoded secret key (secret)

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1598]
#### Currently on:
+ **Commit**:  c3120f2baf8d7b408e228ed08b324566898fb2eb
+ **File**:    [doc/integrations/CORTX-Flask-MediaViewer/app.py](https://github.com/Seagate/cortx/blob/c3120f2baf8d7b408e228ed08b324566898fb2eb/doc/integrations/CORTX-Flask-MediaViewer/app.py)
+ **LineNum**: [12](https://github.com/Seagate/cortx/blob/c3120f2baf8d7b408e228ed08b324566898fb2eb/doc/integrations/CORTX-Flask-MediaViewer/app.py#L12)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33608. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Issue no longer relevant
