### ISSUE TITLE
Possible hardcoded password: 'ldapadmin'

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1599]
#### Currently on:
+ **Commit**:  76d4bd775a1b60c91f6ee58d2b715e8e27ed0fc7
+ **File**:    [doc/integrations/here_cortx_traffic_data.py](https://github.com/Seagate/cortx/blob/76d4bd775a1b60c91f6ee58d2b715e8e27ed0fc7/doc/integrations/here_cortx_traffic_data.py)
+ **LineNum**: [33](https://github.com/Seagate/cortx/blob/76d4bd775a1b60c91f6ee58d2b715e8e27ed0fc7/doc/integrations/here_cortx_traffic_data.py#L33)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33609. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Issue no longer relevant
