### ISSUE TITLE
Move glossary

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#1645]
### Please describe the feature you would like to see added.

We have a glossary currently maintained at https://github.com/Seagate/cortx-k8s/blob/integration/GLOSSARY.md. We need to do the following:
1. Copy the GLOSSARY into the parent repo
2. Replace the content of the current GLOSSARY with a pointer to the new GLOSSARY in the parent repo
3. Edit the README in this parent repo to include a link to the new GLOSSARY

### Please explain why you think adding this feature is important.

Right now it is confusing to keep the global CORTX glossary in the specific k8s repo.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-34180. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by johnbent** [comment]
Fixed in https://github.com/Seagate/cortx/pull/1648 #1648
