### ISSUE TITLE
make: *** No rule to make target `rpms-notests'.  Stop.

### ISSUE THREAD

**Issue by osmboy** [Seagate/cortx#1653]
### Problem

Once the OVA boots and login in, excute build-prep-1node.sh script  just throws an error.

### Expected behavior

build-prep-1node.sh script to git-clone, build and prepare for the 1st startup. It takes about 20 mins to get everything ready

### How to reproduce

Start VM, 
log in ,
```shell
./build-prep-1node.sh
...
Run `make` to build Motr or `make help` for other options
Build Motr rpms...
make: *** No rule to make target `rpms-notests'.  Stop.
```

### Deployment information

VMware ESXi™    Version:     6.7.0 Update 1 (Build 10302608)
Guest OS: Other 3.x Linux (64-bit)
Compatibility Workstation 12 (VM version 12)
VMware Tools: Yes
CPUs: 4
Memory :5.86 GB
Host name: cmu
OVA: https://github.com/Seagate/cortx-motr/releases/tag/ova-centos79

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-34304. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Hi @osmboy I will take a look and see if I can figure out this issue

**Comment by hessio** [comment]
Hi @osmboy so when you get this error you need to move into the cortx-motr directory and run the `make` command

so run these 2 commands:

```
cd cortx-motr
make
```
