### ISSUE TITLE
language 'master ' still in use

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#225]
see https://github.com/Seagate/cortx/search?q=master

multiple docs still use this word

![image](https://user-images.githubusercontent.com/68423216/92218692-1322ac80-eecc-11ea-8e3c-ed263d603fa6.png)

need to do a complete search and replace the word

**Comment by johnbent** [comment]
@Saumya-Sunder , can you take this one please?

https://github.com/Seagate/cortx/search?q=master

Clean up all of these except for the one that says, "Our convention is to not use master".  Obviously, that should remain.  So please clean them up so that the link (https://github.com/Seagate/cortx/search?q=master) shows only one result. Thanks!

**Comment by Saumya-Sunder** [comment]
Hey @johnbent done here https://github.com/Seagate/cortx/pull/453

**Comment by Saumya-Sunder** [comment]
Fixed here https://github.com/Seagate/cortx/pull/453
