### ISSUE TITLE
Noobish question: where does the data /actually/ live in the OVF deployment?

### ISSUE THREAD

**Issue by voyager529** [Seagate/cortx#430]
So, I spun up Cortx on my ESXi host...but having read basically-everything I could find, I'm still missing an a-HA! moment somewhere...

For a bit of context, I have an ESXi host that lives on my lab LAN, along with a FreeNAS build. I've got Minio running on the FreeNAS via its S3 communications option. The ESXi doesn't have a meaningful amount of storage available to it, so the ultimate goal is to compare Cortx to Minio and see how it fares. I'm not a super huge enterprise user or anything, but I am interested in seeing Cortx work...I'm just missing a thing or two and I might not be the only one...

1. The WebUI doesn't seem to allow the ability to define or monitor the storage on the backend. While I was able to figure out how to define buckets, assigning them to a storage volume didn't seem to be readily apparent in the WebUI.

2. I'm assuming that it's intended to have the capacity to point data to something other than the included hard disks, as 20/50/50GB disk volumes do not a massive storage server make. It'd make a bit more sense that I would be expected to put the VMDK volumes on an NFS or iSCSI share if one of them was a thin-provisioned 16EB volume or something, but that does not seem to be the case.

3.  The WebUI frontend (nor any of the documentation I have read thus far) does not seem to indicate the ability to create an iSCSI/NFS connection.

Really, what I'm missing here is that if Cortx is supposed to send data to hard disks (ideally Seagate ones, obviously), then I would assume that there would be some amount of that function that's handled by Cortx instead of letting VMWare do it. I readily admit to not-being super well versed in this sort of storage functionality, but it may well be worth addressing in the FAQ if this concern is 100% a PEBKAC issue.

**Comment by gregnsk** [comment]
@voyager529 , thank you for your interest in CORTX. 

The VM is provided just to demonstrate basic CORTX functionality but is not intended for production use. It doesn't provide high availability, performance or capacity and there is no guarantee for long term data preservation.

CORTX is an object storage layer which doesn't care much about the underlying storage. We focus on making it shine with particular hardware for mass capacity use cases (we call it Lyve Rack), but CORTX may work with any general purpose local drives. If a customer decides to use an FC or an iSCSI target instead of local drives - it should work too. However, as these options are practically unlimited we're not planning to provide special integrations for them. If you're interested in a particular configuration, you're welcome to test it and provide an installation documentation which we'll gladly publish in CORTX git repository. See an example in https://github.com/Seagate/cortx/tree/main/doc/scaleout
