### ISSUE TITLE
NTP needed on OVA

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#932]
From @RodDaSilvaWCO : Suggestion:  install an ntp service on the Cortx VM and have it automatically syncing to internet time...  I was getting "time skew" errors until I did this when I was working with the VM.  Rose in the community also shared this workaround: [https://medium.com/@vuongtran/how-to-resolve-error-amazon-s3-requesttimetooskewed-5d723dc75735](https://medium.com/@vuongtran/how-to-resolve-error-amazon-s3-requesttimetooskewed-5d723dc75735)

@shailesh-vaidya , can we get this added in the future please?

**Comment by ypise** [comment]
The chrony service is already present and the choice of time server can be set using the CSM web GUI.
CC: @kupranay

**Comment by mukul-seagate11** [comment]
@RodDaSilvaWCO, so the reference link, you had mentioned is of RHEL6 and as suggested you can also configure NTP using chrony which is present in OVA [RHEL7] as,

[root@s3 ~]# rpm -qa |grep chrony
chrony-3.4-1.el7.x86_64

[root@s3 ~]# systemctl status chronyd
● chronyd.service - NTP client/server
   Loaded: loaded (/usr/lib/systemd/system/chronyd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-04-22 03:32:34 UTC; 3h 53min ago
     Docs: man:chronyd(8)
           man:chrony.conf(5)
  Process: 801 ExecStartPost=/usr/libexec/chrony-helper update-daemon (code=exited, status=0/SUCCESS)
  Process: 760 ExecStart=/usr/sbin/chronyd $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 770 (chronyd)
   CGroup: /system.slice/chronyd.service
           └─770 /usr/sbin/chronyd

Apr 22 03:32:34 localhost systemd[1]: Starting NTP client/server...
Apr 22 03:32:34 localhost chronyd[770]: chronyd version 3.4 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP...EBUG)
Apr 22 03:32:34 localhost chronyd[770]: Frequency -10.784 +/- 1.251 ppm read from /var/lib/chrony/drift
Apr 22 03:32:34 localhost systemd[1]: Started NTP client/server.
Apr 22 03:33:07 s3.seagate.com chronyd[770]: Selected source 192.168.142.2

[root@s3 ~]# ls -ltr /etc/chrony.conf
-rw-r--r--. 1 root root 994 Jan 28 08:16 /etc/chrony.conf

[root@s3 ~]# chronyc tracking
Reference ID    : C0A88E02 (shg-wan.seagate.com)
Stratum         : 3
Ref time (UTC)  : Thu Apr 22 07:20:49 2021
System time     : 0.000948857 seconds slow of NTP time
Last offset     : -0.001189162 seconds
RMS offset      : 0.000873724 seconds
Frequency       : 11.256 ppm slow
Residual freq   : -0.014 ppm
Skew            : 0.370 ppm
Root delay      : 0.099131659 seconds
Root dispersion : 0.010294242 seconds
Update interval : 2071.5 seconds
Leap status     : Normal

[root@s3 ~]# chronyc sources
210 Number of sources = 1
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^* ang-it-rtr.wanbb.seagate>     2  10   377   591  -3657us[-4846us] +/-   67ms

**Comment by johnbent** [comment]
Thanks to @r-wambui for providing the first solution to this problem!

**Comment by ypise** [comment]
> @RodDaSilvaWCO, so the reference link, you had mentioned is of CentOS6 and as suggested you can also configure NTP using chrony which is present in OVA [CentOS7] as,
> 
> [root@s3 ~]# rpm -qa |grep chrony
> chrony-3.4-1.el7.x86_64
> 
> [root@s3 ~]# systemctl status chronyd
> ● chronyd.service - NTP client/server
> Loaded: loaded (/usr/lib/systemd/system/chronyd.service; enabled; vendor preset: enabled)
> Active: active (running) since Thu 2021-04-22 03:32:34 UTC; 3h 53min ago
> Docs: man:chronyd(8)
> man:chrony.conf(5)
> Process: 801 ExecStartPost=/usr/libexec/chrony-helper update-daemon (code=exited, status=0/SUCCESS)
> Process: 760 ExecStart=/usr/sbin/chronyd $OPTIONS (code=exited, status=0/SUCCESS)
> Main PID: 770 (chronyd)
> CGroup: /system.slice/chronyd.service
> └─770 /usr/sbin/chronyd
> 
> Apr 22 03:32:34 localhost systemd[1]: Starting NTP client/server...
> Apr 22 03:32:34 localhost chronyd[770]: chronyd version 3.4 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP...EBUG)
> Apr 22 03:32:34 localhost chronyd[770]: Frequency -10.784 +/- 1.251 ppm read from /var/lib/chrony/drift
> Apr 22 03:32:34 localhost systemd[1]: Started NTP client/server.
> Apr 22 03:33:07 s3.seagate.com chronyd[770]: Selected source 192.168.142.2
> 
> [root@s3 ~]# ls -ltr /etc/chrony.conf
> -rw-r--r--. 1 root root 994 Jan 28 08:16 /etc/chrony.conf
> 
> [root@s3 ~]# chronyc tracking
> Reference ID : C0A88E02 (shg-wan.seagate.com)
> Stratum : 3
> Ref time (UTC) : Thu Apr 22 07:20:49 2021
> System time : 0.000948857 seconds slow of NTP time
> Last offset : -0.001189162 seconds
> RMS offset : 0.000873724 seconds
> Frequency : 11.256 ppm slow
> Residual freq : -0.014 ppm
> Skew : 0.370 ppm
> Root delay : 0.099131659 seconds
> Root dispersion : 0.010294242 seconds
> Update interval : 2071.5 seconds
> Leap status : Normal

@mukul-seagate11 
There's a simpler way to do this.
Once OVA is imported, perform the onboarding steps:
1. https://github.com/Seagate/cortx/blob/main/doc/Preboarding_and_Onboarding.rst#onboarding step 5.
or
1. The time server can also be set using the Web GUI dashboard settings menu.

The complexity of chronyd config as mentioned above is abstracted by following either of these steps.

**Comment by r-wambui** [comment]
@mukul-seagate11 I had configured on the web GUI dashboard but still got the same error. I probably had the wrong configuration for the time server.

time-server: time.seagate.com
timezone- GMT+3.00 Africa/Nairobi

**Comment by ypise** [comment]
> @mukul-seagate11 I had configured on the web GUI dashboard but still got the same error. I probably had the wrong configuration for the time server.
> 
> 
> 
> time-server: time.seagate.com
> 
> timezone- GMT+3.00 Africa/Nairobi

`time.seagate.com` won't work.
Try a server on public domain, possibly one from https://tf.nist.gov/tf-cgi/servers.cgi
Or based on your comment above a close proximity one for lower latency from one of: https://www.pool.ntp.org/zone/africa

**Comment by mukul-seagate11** [comment]
@all, If all good then can the issue be closed?

**Comment by RodDaSilvaWCO** [comment]
Yes all good.

**Comment by mukul-seagate11** [comment]
Good to hear that the issues has been resolved
